name: test2
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello world"      
      - name: Install httpd
        run: sudo apt install apache2 
      - run: sudo systemctl start apache2
      - run: sudo systemctl status apache2
