name: test2
on: 
  push:
   branches: 
     - 'master' 
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello world"      
      - name: Install httpd
        run: |
         sudo apt install apache2 
         sudo systemctl start apache2
         sudo systemctl status apache2
